name: AlchemyCraft
version: '${version}'
main: org.leralix.alchemycraft.AlchemyCraft
api-version: '1.20'
softdepend: [Adventure]

commands:
  alchdebug:
    description: debug command of AlchemyCraft
    permission: alchemyCraft.admin
    usage: /<command>


permissions:
  alchemyCraft.admin:
    description: Admin permissions   for AlchemyCraft
    default: op
  alchemyCraft.base:
    description: Player permissions for AlchemyCraft
    default: true