name: AlchemyCraft
version: '${version}'
main: org.leralix.alchemycraft.AlchemyCraft
api-version: '1.20'

permissions:
  alchemyCraft.admin:
    description: Admin permissions   for AlchemyCraft
    default: op
  alchemyCraft.*:
    description: Player permissions for AlchemyCraft
    default: true