package org.leralix.alchemycraft.Items;

public enum ItemKey {


    GOLDEN_BEETROOT,
    ZOMBIE_LEG,
    WATERMELON_JUICE,
    GOLEM_HEART,
    PIG_TROTTER,
    SKELETON_FLESH,
    FUNGAL_EXPLOSIVE,
    GROWTH_POWDER,
    SALT,
    GOLDEN_SOUP,
    ZOMBIE_ELIXIR,
    ZOMBIE_GRATIN, GUNPOWDER_EXPLOSION, ZOMBIE_BROTH
}
